name: Azure Pipelines

trigger:
- main

pool: myagent

variables:
  python.version: '3.7.6'
  azureServiceConnectionId: 'msc'
  projectRoot: $(System.DefaultWorkingDirectory)
  environmentName: 'test'

stages:
  - stage: CreateInfrastructure
    jobs:
      - job: BuildInfrastructure
        steps:
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
            displayName: "Terraform installation"
            inputs:
              terraformVersion: "1.5.5"

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
            displayName: "Terraform init"
            inputs:
              provider: "azurerm"
              command: "init"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/environments/test"
              backendServiceArm: "$(azureServiceConnectionId)"
              backendAzureRmResourceGroupName: "Azuredevops"
              backendAzureRmStorageAccountName: "tfstate7367389"
              backendAzureRmContainerName: "tfstate"
              backendAzureRmKey: "test.terraform.tfstate"

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
            displayName: "Terraform validate"
            inputs:
              provider: "azurerm"
              command: "validate"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/environments/test"

          # Script for Terraform Import
          - script: |
              terraform -chdir=$(System.DefaultWorkingDirectory)/terraform/environments/test import module.resource_group.azurerm_resource_group.test /subscriptions/88062415-5d83-43de-899d-8569bf79782b/resourceGroups/Azuredevops
            displayName: 'Terraform Import'


          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
            displayName: "Terraform apply"
            inputs:
              provider: "azurerm"
              command: "apply"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/environments/test"
              environmentServiceNameAzureRM: "$(azureServiceConnectionId)"
